### ISSUE TITLE
Mobile version (Medic list) - Reduce the gap between medic's image and details 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#168]
Mobile version (Medic list) - Reduce the gap between medic's image and details . Please find the screenshot for the reference https://screencast.com/t/faJDktzEdY

**Comment by isohammukherjee** [comment]
this is due to old image resolution, now the dimensions have changed, hence, with new images it won't happen...

**Comment by anirbit** [comment]
Fixed
