### ISSUE TITLE
Search field is not accepting discussion title as the input keyword

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#217]
Search field is not accepting discussion title as the input keyword .
Please find the steps for the reference -
1. Click on Forum
2. Select a topic for ex- Accidents and Injuries
3. Select a discussion "Broken leg and plastic surgery (skin flap)"
4. Copy "Broken leg and plastic surgery (skin flap)" 
5. Back from the topic details page to forum main screen
6. Paste the text and search it https://screencast.com/t/H6uJQkQpZo4 , I am getting a blank screen https://screencast.com/t/bNWkI3c1TAjN

**Comment by anirbit** [comment]
fixed
