### ISSUE TITLE
when any user wants to follow any topic , he clicks on follow  and a confirmation dialogue appears whether to follow or not. If User clicks on yes then the message immediately gets changed to do you want to unfollow the topic .

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#221]
when any user wants to follow any topic , he clicks on follow  and a confirmation dialogue appears whether to follow or not. If User clicks on yes then the message immediately gets changed to "do you want to unfollow the topic" .Please find the video for the reference https://screencast.com/t/IJVagU3qBsG5

**Comment by Rabiteks** [comment]
fixed

**Comment by anirbit** [comment]
Fixed
