### ISSUE TITLE
In forum discussion, if there is no discussion waiting for the reply then don't show the "can you assist field "

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#222]
In forum discussion, if there is no discussion waiting for the reply then don't show the "can you assist field ". Please find the screenshot for the reference https://screencast.com/t/UKBh4Uwfr

**Comment by anirbit** [comment]
Issue not fixed. If there is no discussion then the text should be " No discussion for this topic "

**Comment by anirbit** [comment]
Can you assist section issue has been fixed but if there is no active discussion then don't show the text " Active Discussion in this topic"

Follow the screenshot of the issue => https://screencast.com/t/HtS9ff3xYakb

**Comment by anirbit** [comment]
Fixed
