### ISSUE TITLE
The page should get refreshed immediately when any user post any new discussion for any particular topic.

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#228]
The page should get refreshed immediately when any user post any new discussion for any particular topic.

**Comment by PaulamiSen** [comment]
not fixed . Please find the screenshot for the reference https://screencast.com/t/nUSlIeMKsZ . 
Please follow the steps for the reference -
1. Chose one topic for eg- Oral steroids (Which had no discussion)
2. Click on New discussion
3. My post  is displaying under "Can you assist section" as well as under "Active discussion"

**Comment by anirbit** [comment]
Fixed
