### ISSUE TITLE
Same Discussion displaying in can you assits section and Active discussion section.

### ISSUE THREAD

**Issue by anirbit** [MedicRadar/MedicR#229]
Whenever there is more than one discussion title under "can you assist section" and any user is giving a reply to one of the discussions the other discussion is also changing its status to active discussions along with " can you assist section".

Follow the screenshot of the issue => https://screencast.com/t/YXBzpDow

**Comment by Rabiteks** [comment]
Active discussion is list of all discussion in order to comment count. If no comment it will be listed in last.

**Comment by anirbit** [comment]
Fixed
