### ISSUE TITLE
Search bar is not working in discussion details screen 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#235]
Search bar is not working in discussion details screen . Please find the screenshot for 
 the reference https://screencast.com/t/MldhCsOD

**Comment by Rabiteks** [comment]
This search is only working on comments search.

**Comment by anirbit** [comment]
Search functionality not working properly. Whenever I am searching for a keyword which is already present in comment section, instead of showing the particular comment, the section  is  getting collapsed
Follow the video => https://screencast.com/t/VkiAvsf8

**Comment by anirbit** [comment]
Fixed
