### ISSUE TITLE
Edit profile - When any user deletes any of his clinic address , a confirmation dialogue box gets appeared but when he clicks on yes the values got deleted but the popup remains there 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#270]
Edit profile - When any user deletes any of his clinic address , a confirmation dialogue box gets appeared but when he clicks on yes the values got deleted but the popup remains there . Please find the screenshot for the reference https://screencast.com/t/aOsDEW2mg6D

**Comment by anirbit** [comment]
Fixed

**Comment by PaulamiSen** [comment]
https://screencast.com/t/RKDuphQNT , if you have two clinic address and you delete 1st clinic address then in the confirmation screen it is coming .

**Comment by anirbit** [comment]
Fixed
