### ISSUE TITLE
Many a times after updating any data in edit profile I am receiving this  for example I am updating any data and clicking on save there is no response so to avoid that i am refreshing the screen and i am getting that "Something went wrong"

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#271]
Many a times after updating any data in edit profile I am receiving this  for example I am updating any data and clicking on save there is no response so to avoid that i am refreshing the screen and i am getting that "Something went wrong" . Please find the screenshot for the reference https://screencast.com/t/0xsadYSVmCBz

**Comment by anirbit** [comment]
Fixed
