### ISSUE TITLE
Edit profile - The edit clinic address comes blank while edit clinic address (though there are fields). Please find the screenshot for the reference https://screencast.com/t/3ZzxMWsn0oU

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#272]
Edit profile - The edit clinic address comes blank while edit clinic address (though there are fields). Please find the screenshot for the reference https://screencast.com/t/3ZzxMWsn0oU . Please follow the following steps for the reference -
1. Add 2nd clinic address and save it
2. delete first clinic address 
3. Edit the 2nd clinic address 
4. All the fields are blank is displaying

**Comment by anirbit** [comment]
Add a clinic address with valid street address , whenever editing the created clinic address the street address and address are same. But street address should be different than address.
Follow the screenshot of the issue => https://www.screencast.com/t/sXurLr0MhGDS

**Comment by anirbit** [comment]
Fixed
