### ISSUE TITLE
Edit profile for User - I am receiving something went wrong while I am updating profile image along with the new password 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#324]
Edit profile for User - I am receiving something went wrong while I am updating profile image along with the new password .
1. Change the password
2. Remove the image 
3. Update the profile

**Comment by Rabiteks** [comment]
Issue not replicated.

**Comment by PaulamiSen** [comment]
Please find the video for the reference https://screencast.com/t/pFJ2tHvGWB

**Comment by anirbit** [comment]
Fixed
