### ISSUE TITLE
profession list showing after clicking on reset button.

### ISSUE THREAD

**Issue by anirbit** [MedicRadar/MedicR#36]
Previous profession list showing after clicking the reset button.

Test Step: 1. open the website 
                  2. select location
                  3. Select a symptom 
                  4. select all the profession then click on the next button
                  5. Click on the reset button 
                  6. click on the profession dropdown.

**Comment by anirbit** [comment]
Not fixed

**Comment by Rabiteks** [comment]
Fixed
