### ISSUE TITLE
Most Suitable function does not work according to RTM logic

### ISSUE THREAD

**Issue by anirbit** [MedicRadar/MedicR#38]
Most Suitable - will reapply the original filter and remove any sorting.
If user applied any sorting then by clicking on the most suitable button all the selected sorting options are removed and again reapply the original search criteria.

**Comment by Rabiteks** [comment]
I’ve merged Recommended, Highest Price, Lowest Price, Nearby etc as a dropdown “Sortby”.


[11:42] 
You can now sort the search result by : Recommended, Nearby, Highest Price & Lowest Price

**Comment by anirbit** [comment]
Highest price, Lowest price, Nearby and Recommended are working.
