### ISSUE TITLE
Background color 

### ISSUE THREAD

**Issue by anirbit** [MedicRadar/MedicR#46]
Background color not matched.

Follow the screenshot => https://screencast.com/t/MqgOIae3X1

**Comment by isohammukherjee** [comment]
But in the design given to me, it was this color.. which 1 should I keep?
![search by symptoms - insurance](https://user-images.githubusercontent.com/32636550/32644063-4f34893e-c605-11e7-90c7-bc3103883929.png)

**Comment by anirbit** [comment]
As per discussion the background color will remain same.
