### ISSUE TITLE
No dropdown list is displaying while I am providing any valid or invalid locations in Firefox browser

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#50]
No dropdown list is displaying while I am providing any valid or invalid locations in Firefox browser.
Please find the screenshot for the reference https://screencast.com/t/gVvBCzP777Ka
Steps to be followed -
1. Enter three keywords
2. Select an address from the dropdown by using keypad enter
3. Remove the selected address 
4. Again enter three keywords .

**Comment by anirbit** [comment]
Fixed
