### ISSUE TITLE
Transition is not the same

### ISSUE THREAD

**Issue by anirbit** [MedicRadar/MedicR#51]
skipping between the two types of searches in the middle of a search the transition is not the same. Once in the bottom to top and the other is 45 degrees.

**Comment by Rabiteks** [comment]
Issue is not replicated.

**Comment by anirbit** [comment]
For replicating the issue please follow the below-mentioned screencast video
screencast video => https://screencast.com/t/3XURq3KvDoxw

**Comment by anirbit** [comment]
Fixed
