### ISSUE TITLE
User is not getting any dropdown of locations .

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#60]
User is not getting any dropdown of locations .
Please find the video for the reference -https://screencast.com/t/GcgLmYSljPW
Steps to be followed -
1. Open the website 
2. Search for any location =>symptoms =>professions
3.The user is getting redirected to the search result page 
4.User is refreshing the page 
5. User is getting no result found(which is not supposed to come)
6. User clicks on the back button
7. Instead of getting redirected to the the home url (https://172.104.180.108/) user is getting redirected to the https://172.104.180.108/#
8.Now when user is searching for a location with a valid input 
9.No result is displaying

**Comment by anirbit** [comment]
fixed
