### ISSUE TITLE
Search result page - UI needs to be fixed 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#61]
Search result page - UI needs to be fixed 
Please find the screenshot for the reference https://screencast.com/t/OB4GFtLHa
Steps to be followed -
1. Search  any symptoms/professions (be it guided search or manual search) 
for example -
a . location = london ,UK 
b . Symptoms = Headache,migrain
c . Profession = Chiropractic
d . Get redirected to the search result  page
e. Select language (when there is 0 result found)

**Comment by anirbit** [comment]
Fixed
