### ISSUE TITLE
(Mobile version) Search result screen - While tapping over reset the my screen is displaying with black coloured fields 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#70]
Search result screen - While tapping over reset the my screen is displaying with black coloured fields .  Please find the screenshot for the reference https://screencast.com/t/N8PafhXx

**Comment by isohammukherjee** [comment]
the loader is not getting loaded, i am not controlling it through front end

**Comment by anirbit** [comment]
not fixed

**Comment by anirbit** [comment]
fixed
