### ISSUE TITLE
Mobile version - UI needs to be fixed in location dropdown for search result screen 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#71]
Mobile version - UI needs to be fixed in location dropdown for search result screen . Please find the screenshot for the reference https://screencast.com/t/aReSEOxhaTw

**Comment by isohammukherjee** [comment]
the loader is not getting loaded, i am not controlling it through front end

**Comment by anirbit** [comment]
Not fixed
