### ISSUE TITLE
The validation message remain present after reseting the search criteria 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#78]
The validation message remain present after reseting the search criteria . Please find the screenshot for the reference https://screencast.com/t/0xjRejNHDqJ .
Steps to be followed -
1. Search by symptoms/profession from manual/guided search 
2. Reset all values in search result screen 
3.Sort gender (by male/female) or any values and click on search 
4. Click on reset 
5. The validation message remains present .

**Comment by anirbit** [comment]
Fixed
