### ISSUE TITLE
 Feedback of Sir dated on 10.11.17

### ISSUE THREAD

**Issue by anirbit** [MedicRadar/MedicR#81]
1.Font of search result page.
2.1,2,3 alignment
3.Gap between tab
4.placeholder in middle
5.dotted lines in tab selection
6.mouse hover in ">" button
7. "<" icon not needed for the first time.
8.1,2,3 clickable
9. Sentence case symptom name
10.loader to integrate after search
11. slider will come from the box

**Comment by isohammukherjee** [comment]
UI issues resolved..

**Comment by anirbit** [comment]
Fixed
