### ISSUE TITLE
In search result page (by manual search) - If I am tapping over search by profession link ,I should get redirected to the manual search page whereas I am getting redirected to the guided search page 

### ISSUE THREAD

**Issue by PaulamiSen** [MedicRadar/MedicR#82]
In search result page (by manual search) - If I am tapping over search by profession link ,I should get redirected to the manual search page instead of getting redirected to the guided search page .
Please find the following steps below -
1.Click on skip to manual search
2. Select search by profession /symptom 
3. Select postal code 
4. Search by profession
5. Select specialism
6. Click on search
7. Click on search by profession
I am getting redirected to the search by symptoms under guided search .

Also find the video for the reference https://screencast.com/t/vUPh1C3Ny

**Comment by anirbit** [comment]
Closed
